{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.otelCollector.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.otelCollector.name }}
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/part-of: trainticket
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.otelCollector.name }}
  labels:
    app: {{ .Values.otelCollector.name }}
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/part-of: trainticket
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.otelCollector.name }}
  labels:
    app: {{ .Values.otelCollector.name }}
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/part-of: trainticket
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Values.otelCollector.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.otelCollector.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
